In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import gc
import os

C:\Users\natrajsekarvs\AppData\Local\Temp\ipykernel_17156\3244632070.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
import os, psutil
process = psutil.Process(os.getpid())
process.memory_info().rss / (1024 * 1024)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [3]:
gc.collect()

0

In [4]:
stage_1_list ="'0-1"
stage_2_list =["'1-2","'2-3"]
stage_3_list =["'3-4","'4-5","'5-6","'6-7","'7+"]

In [5]:
sub_prod_mast=pd.read_csv(r'D:\New folder\Master\sub_prod_mast.csv')
zone_mast =pd.read_csv(r'D:\New folder\Master\Zone.csv')
addn_stage3 = pd.read_csv(r'D:\New folder\Master\Additionalstage3.csv')
pre_x = pd.read_csv(r'D:\New folder\Master\Prex.csv')
covid = pd.read_csv(r'D:\New folder\Master\Covid Rest.csv')
rev_gv = pd.read_csv(r'D:\New folder\Master\Rev_gv.csv')
otherod_gv = pd.read_csv(r'D:\New folder\Master\Other_od.csv')
pd_mast1 = pd.read_csv(r'D:\New folder\Master\PD File1.csv')
pd_mast2 = pd.read_csv(r'D:\New folder\Master\PD File2.csv')
pd_mast3 = pd.read_csv(r'D:\New folder\Master\PD File3.csv')
pd_mast4 = pd.read_csv(r'D:\New folder\Master\PD File4.csv')

In [6]:
pd_mast = pd.concat([pd_mast1,pd_mast2,pd_mast3,pd_mast4],ignore_index=True)
pd_mast

,AGREEMENTNO,SEASONING GRP,PAID TENURE GRP,Final Status,POS Comfort Flag,Last Month_Stage,Last Month_Deli-Remarks
0,XVFPGIR00004149926,'25-35,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal
1,XVFPOHA00005641695,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2,XVFPGDC00006453353,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
3,XVFPBIS00005378294,'13-18,PAID <25%,Paid 0 out of 1,NaN,Stage 1,Normal
4,XVFPALK00006409974,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
...,...,...,...,...,...,...,...
2535597,XTRARMG00006090478,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
2535598,XTRABWI00005555355,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2535599,XTRASUM00005503223,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2535600,XTRAMAJ00003811602,'36+,PAID 50%-74%,Paid 4 out of 4,NaN,Stage 1,Normal
2535601,XTRANLR00004363738,'25-35,PAID >=75%,Paid 4 out of 4,NaN,Stage 1,Normal

In [7]:
pd_mast['SEASONING GRP']=pd_mast['SEASONING GRP'].apply(lambda x: "'" + x if not x.startswith("'") else x)

In [8]:
#pd_mast['SEASONING GRP'] = "'" + pd_mast['SEASONING GRP'].astype(str)

In [9]:
pd_mast

,AGREEMENTNO,SEASONING GRP,PAID TENURE GRP,Final Status,POS Comfort Flag,Last Month_Stage,Last Month_Deli-Remarks
0,XVFPGIR00004149926,'25-35,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal
1,XVFPOHA00005641695,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2,XVFPGDC00006453353,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
3,XVFPBIS00005378294,'13-18,PAID <25%,Paid 0 out of 1,NaN,Stage 1,Normal
4,XVFPALK00006409974,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
...,...,...,...,...,...,...,...
2535597,XTRARMG00006090478,'0-6,PAID <25%,<4 Month,NaN,Stage 1,Normal
2535598,XTRABWI00005555355,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2535599,XTRASUM00005503223,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
2535600,XTRAMAJ00003811602,'36+,PAID 50%-74%,Paid 4 out of 4,NaN,Stage 1,Normal
2535601,XTRANLR00004363738,'25-35,PAID >=75%,Paid 4 out of 4,NaN,Stage 1,Normal

In [10]:
ce=pd.read_csv(r'D:\New folder\IT\deliquency_CE.csv',encoding= 'unicode_escape')
shubh=pd.read_csv(r'D:\New folder\IT\deliquency_SHUBH.csv',encoding= 'unicode_escape')
tractor=pd.read_csv(r'D:\New folder\IT\deliquency_TRACTOR.csv',encoding= 'unicode_escape')
vfp=pd.read_csv(r'D:\New folder\IT\deliquency_VFPRIME.csv',encoding= 'unicode_escape')
vfp1=pd.read_csv(r'D:\New folder\IT\deliquency_VFPRIME_1.csv',encoding= 'unicode_escape')

In [11]:
ce['APP_FORMNO']=ce['APP_FORMNO'].astype(str)
shubh['APP_FORMNO']=shubh['APP_FORMNO'].astype(str)
tractor['APP_FORMNO']=tractor['APP_FORMNO'].astype(str)
vfp['APP_FORMNO']=vfp['APP_FORMNO'].astype(str)
vfp1['APP_FORMNO']=vfp1['APP_FORMNO'].astype(str)

In [12]:
df=[ce,shubh,tractor,vfp,vfp1]

itdel_dump= pd.concat(df,ignore_index=True,sort=False)

In [13]:
itdel_dump

,AGREEMENTNO,CUSTOMERID,PRODUCT,SCHEMEDESC,BRANCH_NAME,CUSTOMERNAME,TENURE,AUTHDATE,REPAYMENT_MODE,EMI,...,REVISED_FINAL_DPD,MORATORIUM_PERIOD,MORATORIUM_STARTDATE,MORATORIUM_ENDDATE,CIF_NO,REGDNUM,OTHER_OD,SMA_STAGE,SMA_STAMPING_DATE,SMA_NPA_DATE
0,X0CERAP00005482334,11445023,CE,CE NEW,RAPAR VF,Hamirbhai Lakhamanbhai Varchand,60,2023-03-16 00:00:00.0,NACH,54715.000,...,0,NaN,NaN,NaN,8835258,NaN,NaN,NRML,23-OCT-23,NaN
1,X0CEADN00002838239,94707887,CE,CE NEW,AHMEDNAGAR VF,Ramkisan Nathu Gaikwad,54,2019-03-04 00:00:00.0,NACH,0.000,...,0,45678.000,2020-04-01 00:00:00.0,2020-08-31 00:00:00.0,4114931,NON5808528,0.000,NRML,15-SEP-23,NaN
2,X0CEJHR00003444546,97139953,CE,CE USED,BILARA VF,Hindu Ram,19,2020-01-31 00:00:00.0,NACH,0.000,...,1174,345678.000,2020-03-01 00:00:00.0,2020-08-31 00:00:00.0,4802625,NON6091121,2893.350,NPA3,30-APR-21,30-APR-21
3,X0CEPAM00005402046,10670934,CE,CE USED,K R PURAM VF,KIRAN S,36,2023-02-15 00:00:00.0,NACH,54189.000,...,0,NaN,NaN,NaN,11101138,KA-53-MG-6176,0.000,NRML,17-OCT-23,NaN
4,X0CEBRH00005440726,11293924,CE,CE USED,ORISSA BEHRAMPUR VF,SANTOSH KUMAR PANIGRAHI,36,2023-02-27 00:00:00.0,NACH,52740.000,...,0,NaN,NaN,NaN,3855706,NON5038259,0.000,NRML,27-FEB-23,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543767,XVFPDHS00004802678,7846857,VFPRIME,TWO WHEELER SCHEME,DHARSIWA VF,SANJAY KHAN,24,2022-06-04 00:00:00.0,NACH,3850.000,...,0,NaN,NaN,NaN,9663519,CG-04-NT-8843,3068.000,NRML,26-FEB-24,NaN
2543768,XVFPBGH00006449330,16219721,VFPRIME,TWO WHEELER SCHEME,BARGARH VF,SHIBA MALLICK,30,2024-02-12 00:00:00.0,NACH,6960.000,...,1,NaN,NaN,NaN,14256721,OD-17-AB-5609,236.000,SMA0,15-APR-24,NaN
2543769,XVFPPNU00003868368,99108331,VFPRIME,GECL,PUNALUR VF,MOLLYKUTTY S,48,2020-11-18 00:00:00.0,NPDC,3695.000,...,87,NaN,NaN,NaN,5747791,KL-25-M-3951,16759.000,NPA2,20-MAR-24,18-JUN-22
2543770,XVFPPNE00005922441,13615722,VFPRIME,3WHEELER EV NEW,PURNEA VF,MOHAMMED SADDAM,36,2023-08-21 00:00:00.0,NACH,7960.000,...,0,NaN,NaN,NaN,12601295,BR-11-PC-8137,NaN,NRML,27-SEP-23,NaN
2543771,XVFPJAJ00003816698,98932440,VFPRIME,GECL,ORISSA JAJPUR ROAD VF,SAROJ KUMAR SAHU,48,2020-10-27 00:00:00.0,NPDC,10844.000,...,0,NaN,NaN,NaN,4072851,OR16D1510,472.000,NRML,14-AUG-23,NaN

In [14]:
del ce, tractor, shubh, vfp, vfp1

In [15]:
itdel_dump.drop('AUTHDATE',axis=1,inplace=True)
itdel_dump.drop('EFF_DT',axis=1,inplace=True)
itdel_dump.drop('EMI_START_DATE',axis=1,inplace=True)
itdel_dump.drop('LAST_EMI_DATE',axis=1,inplace=True)
itdel_dump.drop('REPAY_DUEDATE',axis=1,inplace=True)
itdel_dump.drop('CLOSUREDATE',axis=1,inplace=True)
itdel_dump.drop('MORATORIUM_STARTDATE',axis=1,inplace=True)
itdel_dump.drop('MORATORIUM_ENDDATE',axis=1,inplace=True)

In [16]:
itdel_dump

,AGREEMENTNO,CUSTOMERID,PRODUCT,SCHEMEDESC,BRANCH_NAME,CUSTOMERNAME,TENURE,REPAYMENT_MODE,EMI,MI,...,MAD_AMOUNT,OTHER_OD_DPD,REVISED_FINAL_DPD,MORATORIUM_PERIOD,CIF_NO,REGDNUM,OTHER_OD,SMA_STAGE,SMA_STAMPING_DATE,SMA_NPA_DATE
0,X0CERAP00005482334,11445023,CE,CE NEW,RAPAR VF,Hamirbhai Lakhamanbhai Varchand,60,NACH,54715.000,0,...,NaN,0,0,NaN,8835258,NaN,NaN,NRML,23-OCT-23,NaN
1,X0CEADN00002838239,94707887,CE,CE NEW,AHMEDNAGAR VF,Ramkisan Nathu Gaikwad,54,NACH,0.000,0,...,NaN,0,0,45678.000,4114931,NON5808528,0.000,NRML,15-SEP-23,NaN
2,X0CEJHR00003444546,97139953,CE,CE USED,BILARA VF,Hindu Ram,19,NACH,0.000,0,...,NaN,0,1174,345678.000,4802625,NON6091121,2893.350,NPA3,30-APR-21,30-APR-21
3,X0CEPAM00005402046,10670934,CE,CE USED,K R PURAM VF,KIRAN S,36,NACH,54189.000,0,...,NaN,0,0,NaN,11101138,KA-53-MG-6176,0.000,NRML,17-OCT-23,NaN
4,X0CEBRH00005440726,11293924,CE,CE USED,ORISSA BEHRAMPUR VF,SANTOSH KUMAR PANIGRAHI,36,NACH,52740.000,0,...,NaN,0,0,NaN,3855706,NON5038259,0.000,NRML,27-FEB-23,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543767,XVFPDHS00004802678,7846857,VFPRIME,TWO WHEELER SCHEME,DHARSIWA VF,SANJAY KHAN,24,NACH,3850.000,0,...,NaN,0,0,NaN,9663519,CG-04-NT-8843,3068.000,NRML,26-FEB-24,NaN
2543768,XVFPBGH00006449330,16219721,VFPRIME,TWO WHEELER SCHEME,BARGARH VF,SHIBA MALLICK,30,NACH,6960.000,0,...,NaN,0,1,NaN,14256721,OD-17-AB-5609,236.000,SMA0,15-APR-24,NaN
2543769,XVFPPNU00003868368,99108331,VFPRIME,GECL,PUNALUR VF,MOLLYKUTTY S,48,NPDC,3695.000,0,...,NaN,0,87,NaN,5747791,KL-25-M-3951,16759.000,NPA2,20-MAR-24,18-JUN-22
2543770,XVFPPNE00005922441,13615722,VFPRIME,3WHEELER EV NEW,PURNEA VF,MOHAMMED SADDAM,36,NACH,7960.000,0,...,NaN,0,0,NaN,12601295,BR-11-PC-8137,NaN,NRML,27-SEP-23,NaN
2543771,XVFPJAJ00003816698,98932440,VFPRIME,GECL,ORISSA JAJPUR ROAD VF,SAROJ KUMAR SAHU,48,NPDC,10844.000,0,...,NaN,0,0,NaN,4072851,OR16D1510,472.000,NRML,14-AUG-23,NaN

In [17]:
vf1=pd.read_csv(r'D:\New folder\ONLINE_ROLLRATE_EXPT_VFPRIME_2024-04-16_13-59-38.csv',encoding='unicode_escape')
vf2=pd.read_csv(r'D:\New folder\Online_rollrate_VFPRIME_NEW_2024-04-16_13-59-38.csv',encoding='unicode_escape')
vf3=pd.read_csv(r'D:\New folder\Online_rollrate_VFPRIME_USED_2024-04-16_13-59-38.csv',encoding='unicode_escape')
vf4=pd.read_csv(r'D:\New folder\REPOtoREG.csv',encoding='unicode_escape')

In [18]:
vf1.drop('CLOSUREDATE',axis=1,inplace=True)
vf1.drop('TXNDATE',axis=1,inplace=True)
vf1.drop('MORATORIUM_STARTDATE',axis=1,inplace=True)
vf1.drop('MORATORIUM_ENDDATE',axis=1,inplace=True)
vf1.drop('EFF_DT',axis=1,inplace=True)
vf1.drop('RUN_DATE',axis=1,inplace=True)

In [19]:
vf2.drop('CLOSUREDATE',axis=1,inplace=True)
vf2.drop('TXNDATE',axis=1,inplace=True)
vf2.drop('MORATORIUM_STARTDATE',axis=1,inplace=True)
vf2.drop('MORATORIUM_ENDDATE',axis=1,inplace=True)
vf2.drop('EFF_DT',axis=1,inplace=True)
vf2.drop('RUN_DATE',axis=1,inplace=True)

In [20]:
vf3.drop('CLOSUREDATE',axis=1,inplace=True)
vf3.drop('TXNDATE',axis=1,inplace=True)
vf3.drop('MORATORIUM_STARTDATE',axis=1,inplace=True)
vf3.drop('MORATORIUM_ENDDATE',axis=1,inplace=True)
vf3.drop('EFF_DT',axis=1,inplace=True)
vf3.drop('RUN_DATE',axis=1,inplace=True)

In [21]:
vf4.drop('CLOSUREDATE',axis=1,inplace=True)
vf4.drop('TXNDATE',axis=1,inplace=True)
vf4.drop('MORATORIUM_STARTDATE',axis=1,inplace=True)
vf4.drop('MORATORIUM_ENDDATE',axis=1,inplace=True)
vf4.drop('EFF_DT',axis=1,inplace=True)
vf4.drop('RUN_DATE',axis=1,inplace=True)
vf4.replace({pd.NA: ""},inplace=True)

In [22]:
df1=[vf1,vf2,vf3,vf4]

del_dump= pd.concat(df1,ignore_index=True,sort=False)
del_dump

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,LEGAL_INFO,PRIORITY_INFO,POS_COMFORT_GIVEN,UNPAID,POS_COMFORT_STATUS,STABLI_UNPAID,MORATORIUM,MORATORIUM_PERIOD,PREX_DPD,PREX_STATUS
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NaN,NaN,NO,NaN,7-12,NaN,NO,NaN,0.000,0
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NaN,NaN,NO,NaN,13-18,NaN,NO,NaN,0.000,0
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,NaN,UNPAID,NO,YES,7-12,STABILISED,NO,NaN,63.000,2-3
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NaN,NaN,NO,NaN,7-12,NaN,NO,NaN,0.000,0
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NaN,NaN,NO,NaN,25+,NaN,NO,NaN,0.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,NaN,HCV,NaN,NaN,DHARSIWA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,NaN,LCV,NaN,NaN,NAGAON VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KARNAL VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KOLKATTA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,NaN,MUV,NaN,NaN,SHIRPUR VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
del vf1,vf2,vf3,vf4

In [24]:
del_dump['FINAL_NEW_DPD_GRP']=np.where(
    (del_dump['FINAL_NEW_DPD_GRP'].isna()),
    "0-1",
    del_dump['FINAL_NEW_DPD_GRP']
)

In [25]:
del_dump['FINAL_NEW_DPD_GRP']=np.where(
    (del_dump['FINAL_NEW_DPD_GRP']== '0'),
    "0-1",
    del_dump['FINAL_NEW_DPD_GRP']
)

In [26]:
del_dump['FINAL_NEW_DPD_GRP']=np.where(
    (~del_dump['FINAL_NEW_DPD'].isna()) & (del_dump['FINAL_NEW_DPD'] >=215),
    '7+',
    del_dump['FINAL_NEW_DPD_GRP']
)

In [27]:
del_dump.loc[del_dump['FINAL_NEW_DPD_GRP'].isin(['6-7','7+']),'FINAL_NEW_DPD_GRP'] = '6+'

In [28]:
del_dump.loc[del_dump['NPA_STAGE_ID']=='SALE','FINAL_NEW_DPD_GRP'] = 'A/C Closed'

In [29]:
del_dump.loc[del_dump['CLNPA_GRP'].isin(['6-7','7+']),'CLNPA_GRP'] = '6+'

In [30]:
del_dump['FINAL_CLNPA_DPD_GRP']=np.where(
    (del_dump['CLNPA_GRP'].isna() | (del_dump['CLNPA_GRP']=="")),
    del_dump['FINAL_NEW_DPD_GRP'],
    del_dump['CLNPA_GRP']
)

In [31]:
del_dump['FINAL_NEW_DPD_GRP'] = "'" + del_dump['FINAL_NEW_DPD_GRP'].astype(str)
del_dump['CLNPA_GRP'] = "'" + del_dump['CLNPA_GRP'].astype(str)
del_dump['FINAL_CLNPA_DPD_GRP'] = "'" + del_dump['FINAL_CLNPA_DPD_GRP'].astype(str)

In [32]:
del_dump['FINAL_CLNPA_DPD_GRP']

0          '0-1
1          '0-1
2          '1-2
3          '0-1
4          '0-1
           ...
2527806    '0-1
2527807    '1-2
2527808    '1-2
2527809     '6+
2527810    '0-1
Name: FINAL_CLNPA_DPD_GRP, Length: 2527811, dtype: object

In [33]:
del_dump_aadn=pd.merge(del_dump,addn_stage3[['AGREEMENTNO','Remarks']],on='AGREEMENTNO',how='left')
del_dump_aadn

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,POS_COMFORT_GIVEN,UNPAID,POS_COMFORT_STATUS,STABLI_UNPAID,MORATORIUM,MORATORIUM_PERIOD,PREX_DPD,PREX_STATUS,FINAL_CLNPA_DPD_GRP,Remarks
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NO,NaN,7-12,NaN,NO,NaN,0.000,0,'0-1,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NO,NaN,13-18,NaN,NO,NaN,0.000,0,'0-1,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,NO,YES,7-12,STABILISED,NO,NaN,63.000,2-3,'1-2,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NO,NaN,7-12,NaN,NO,NaN,0.000,0,'0-1,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NO,NaN,25+,NaN,NO,NaN,0.000,0,'0-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,NaN,HCV,NaN,NaN,DHARSIWA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'0-1,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,NaN,LCV,NaN,NaN,NAGAON VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'1-2,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KARNAL VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'1-2,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KOLKATTA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'6+,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,NaN,MUV,NaN,NaN,SHIRPUR VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'0-1,NaN

In [34]:
del_dump_aadn.columns=del_dump_aadn.columns.str.replace('Remarks','ADDN_STG3')

In [35]:
del_dump_aadn

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,POS_COMFORT_GIVEN,UNPAID,POS_COMFORT_STATUS,STABLI_UNPAID,MORATORIUM,MORATORIUM_PERIOD,PREX_DPD,PREX_STATUS,FINAL_CLNPA_DPD_GRP,ADDN_STG3
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NO,NaN,7-12,NaN,NO,NaN,0.000,0,'0-1,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NO,NaN,13-18,NaN,NO,NaN,0.000,0,'0-1,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,NO,YES,7-12,STABILISED,NO,NaN,63.000,2-3,'1-2,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NO,NaN,7-12,NaN,NO,NaN,0.000,0,'0-1,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NO,NaN,25+,NaN,NO,NaN,0.000,0,'0-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,NaN,HCV,NaN,NaN,DHARSIWA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'0-1,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,NaN,LCV,NaN,NaN,NAGAON VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'1-2,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KARNAL VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'1-2,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KOLKATTA VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'6+,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,NaN,MUV,NaN,NaN,SHIRPUR VF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'0-1,NaN

In [36]:
condition=(del_dump_aadn['FINAL_CLNPA_DPD_GRP'].isin(["'0-1","'1-2","'2-3" ])) & (~del_dump_aadn['ADDN_STG3'].isin([None,np.nan, ""]))
del_dump_aadn.loc[condition,'FINAL_CLNPA_DPD_GRP'] = "'3-4"

In [37]:
del_dump_co=pd.merge(del_dump_aadn,covid[['AGREEMENTNO','FEB DPD','FEB DPD GRP','COVID_STAGE']],on='AGREEMENTNO',how='left')
del_dump_co

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,STABLI_UNPAID,MORATORIUM,MORATORIUM_PERIOD,PREX_DPD,PREX_STATUS,FINAL_CLNPA_DPD_GRP,ADDN_STG3,FEB DPD,FEB DPD GRP,COVID_STAGE
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NaN,NO,NaN,0.000,0,'0-1,NaN,NaN,NaN,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NaN,NO,NaN,0.000,0,'0-1,NaN,NaN,NaN,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,STABILISED,NO,NaN,63.000,2-3,'1-2,NaN,NaN,NaN,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NaN,NO,NaN,0.000,0,'0-1,NaN,NaN,NaN,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NaN,NO,NaN,0.000,0,'0-1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,NaN,HCV,NaN,NaN,DHARSIWA VF,...,NaN,NaN,NaN,NaN,NaN,'0-1,NaN,NaN,NaN,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,NaN,LCV,NaN,NaN,NAGAON VF,...,NaN,NaN,NaN,NaN,NaN,'1-2,NaN,NaN,NaN,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KARNAL VF,...,NaN,NaN,NaN,NaN,NaN,'1-2,NaN,NaN,NaN,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KOLKATTA VF,...,NaN,NaN,NaN,NaN,NaN,'6+,NaN,NaN,NaN,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,NaN,MUV,NaN,NaN,SHIRPUR VF,...,NaN,NaN,NaN,NaN,NaN,'0-1,NaN,NaN,NaN,NaN

In [38]:
del_dump_co.loc[del_dump_co['COVID_STAGE'].isna(),'AGREEMENTNO'].unique()

array(['XSHUDAV00005613273', 'XTRAURY00004838916', 'XSHUARI00005864298',
       ..., 'XVFPKAL00004472403', 'XVFPKAT00004232808',
       'XVFPSPH00005481420'], dtype=object)

In [39]:
del_dump_re=pd.merge(del_dump_co,rev_gv[['AGREEMENTNO','REV_GV']],on='AGREEMENTNO',how='left')

In [40]:
del_dump_re.loc[del_dump_re['REV_GV'].isna(),'AGREEMENTNO'].unique()

array(['XSHUDAV00005613273', 'XTRAURY00004838916', 'XSHUARI00005864298',
       ..., 'XVFPKAL00004472403', 'XVFPKAT00004232808',
       'XVFPSPH00005481420'], dtype=object)

In [41]:
del_dump_ot=pd.merge(del_dump_re,otherod_gv[['AGREEMENTNO','CHARGEDESC','RECEIVABLES_OTHEROD']],on='AGREEMENTNO',how='left')
del_dump_ot

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,PREX_DPD,PREX_STATUS,FINAL_CLNPA_DPD_GRP,ADDN_STG3,FEB DPD,FEB DPD GRP,COVID_STAGE,REV_GV,CHARGEDESC,RECEIVABLES_OTHEROD
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,0.000,0,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,0.000,0,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,63.000,2-3,'1-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,0.000,0,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,0.000,0,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,NaN,HCV,NaN,NaN,DHARSIWA VF,...,NaN,NaN,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,NaN,LCV,NaN,NaN,NAGAON VF,...,NaN,NaN,'1-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KARNAL VF,...,NaN,NaN,'1-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,NaN,LCV,NaN,NaN,KOLKATTA VF,...,NaN,NaN,'6+,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,NaN,MUV,NaN,NaN,SHIRPUR VF,...,NaN,NaN,'0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
conditions = [
    (del_dump_ot['FINAL_NEW_DPD'] >= 1095),
    (del_dump_ot['FINAL_NEW_DPD'] >= 730),
    (del_dump_ot['FINAL_NEW_DPD'] >= 365),
    (del_dump_ot['FINAL_NEW_DPD'] >= 212),
    (del_dump_ot['FINAL_NEW_DPD'] >= 181),
]

choice=["'36+","'24-36","'12-24","'7-12","'6-7"]

del_dump_ot['Day_grp'] = np.select(conditions,choice,default="'3-6")

In [43]:
conditions1 = [
    (del_dump_ot['FINAL_NEW_DPD'] >= 1095),
    (del_dump_ot['FINAL_NEW_DPD'] >= 911),
    (del_dump_ot['FINAL_NEW_DPD'] >= 730),
    (del_dump_ot['FINAL_NEW_DPD'] >= 546),
    (del_dump_ot['FINAL_NEW_DPD'] >= 365),
    (del_dump_ot['FINAL_NEW_DPD'] >= 212),
    (del_dump_ot['FINAL_NEW_DPD'] >= 181),
]

choice1=["'36+","'30-36","'24-30","'18-24","'12-18","'7-12","'6-7"]

del_dump_ot['PROday_grp'] = np.select(conditions1,choice1,default="'3-6")

In [44]:
del_dump_ot.replace({pd.NA: ""},inplace=True)

In [45]:
del_dump_ot['Deli_Remarks'] = del_dump_ot.apply(
    lambda row: row['ADDN_STG3'] if row['ADDN_STG3'] != ""
    else "CLNPA_3-7" if row['CLNPA_GRP'] == "'3-4"
    else "CLNPA_7+" if row['CLNPA_GRP'] =="'6+"
    else "Normal",axis=1
)

In [46]:
del_dump_ot['FINAL_CLNPA_DPD_GRP'] = del_dump_ot.apply(
    lambda row: "'1-2" if row['FINAL_NEW_DPD_GRP']=="'0-1" and row['Deli_Remarks']=="Normal" and row['COVID_STAGE'] !=""
    else row['FINAL_CLNPA_DPD_GRP'],
    axis=1
)

In [47]:
del_dump_ot['FINAL_CLNPA_DPD_GRP']

0          '0-1
1          '0-1
2          '1-2
3          '0-1
4          '0-1
           ...
2527806    '0-1
2527807    '1-2
2527808    '1-2
2527809     '6+
2527810    '0-1
Name: FINAL_CLNPA_DPD_GRP, Length: 2527811, dtype: object

In [48]:
del_dump_ot['REV_CUR_OD_PLUS_POS'] = np.where(
   (~del_dump_ot['REV_GV'].isna()) & (del_dump_ot['REV_GV'] !="") & (del_dump_ot['FLAG'] !="P"),
   del_dump_ot['REV_GV'],
   del_dump_ot['REV_CUR_OD_PLUS_POS']
)

In [49]:
del_dump_it=pd.merge(del_dump_ot,itdel_dump[['AGREEMENTNO','CIF_NO','NPA_STAGEID','SMA_STAGE']],on='AGREEMENTNO',how='left')
del_dump_it

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,COVID_STAGE,REV_GV,CHARGEDESC,RECEIVABLES_OTHEROD,Day_grp,PROday_grp,Deli_Remarks,CIF_NO,NPA_STAGEID,SMA_STAGE
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,,,,NaN,'3-6,'3-6,Normal,9811944.000,REGULAR,NRML
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,,,,NaN,'3-6,'3-6,Normal,9725968.000,REGULAR,NRML
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,,,,NaN,'3-6,'3-6,Normal,9537813.000,REGULAR,SMA1
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,,,,NaN,'3-6,'3-6,Normal,12020607.000,REGULAR,NRML
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,,,,NaN,'3-6,'3-6,Normal,8342220.000,REGULAR,NRML
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,,,,NaN,'3-6,'3-6,Normal,6753610.000,REGULAR,NRML
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,,,,NaN,'3-6,'3-6,Normal,5490709.000,REGULAR,NPA0
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,,,,NaN,'3-6,'3-6,Normal,8886555.000,REGULAR,NPA0
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,,,,NaN,'6-7,'6-7,Normal,618521.000,REGULAR,NPA3
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,,,,NaN,'3-6,'3-6,Normal,7074060.000,REGULAR,SMA0

In [50]:
del_dump_it.loc[del_dump_it['CIF_NO'].isna(),'AGREEMENTNO'].unique()

array(['XTRAMRE00004050269', 'XVFPRUH00004119069', 'XVFPHVF00004078782',
       ..., 'XVFPDAL00005476954', 'XVFPIRS00005806265',
       'XVFPANM00005006633'], dtype=object)

In [51]:
del_dump_it.replace({pd.NA: ""},inplace=True)

In [52]:
del_dump_it['SMA_STAGE']=np.where(
    (del_dump_it['SMA_STAGE'].isin(['NPA0','NPA1','NPA2'])),
    'NPAS12',
    del_dump_it['SMA_STAGE']
)

In [53]:
del_dump_it

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,COVID_STAGE,REV_GV,CHARGEDESC,RECEIVABLES_OTHEROD,Day_grp,PROday_grp,Deli_Remarks,CIF_NO,NPA_STAGEID,SMA_STAGE
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,,,,NaN,'3-6,'3-6,Normal,9811944.000,REGULAR,NRML
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,,,,NaN,'3-6,'3-6,Normal,9725968.000,REGULAR,NRML
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,,,,NaN,'3-6,'3-6,Normal,9537813.000,REGULAR,SMA1
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,,,,NaN,'3-6,'3-6,Normal,12020607.000,REGULAR,NRML
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,,,,NaN,'3-6,'3-6,Normal,8342220.000,REGULAR,NRML
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,,,,NaN,'3-6,'3-6,Normal,6753610.000,REGULAR,NRML
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,,,,NaN,'3-6,'3-6,Normal,5490709.000,REGULAR,NPAS12
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,,,,NaN,'3-6,'3-6,Normal,8886555.000,REGULAR,NPAS12
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,,,,NaN,'6-7,'6-7,Normal,618521.000,REGULAR,NPA3
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,,,,NaN,'3-6,'3-6,Normal,7074060.000,REGULAR,SMA0

In [54]:
f=del_dump_it[(del_dump_it['SMA_STAGE']=='NPAS12') & (del_dump_it['NPA_STAGEID']!='WRITEOFF')]
f1=f[['CIF_NO']].drop_duplicates()

f1.to_csv("C:\\Users\\natrajsekarvs\\Downloads\\MaxCIF_NO.csv",index=False)

In [55]:
MaxCIF_No=pd.read_csv(r'C:\Users\natrajsekarvs\Downloads\MaxCIF_NO.csv')
MaxCIF_No

            CIF_NO
0      9094333.000
1      6626700.000
2     11396374.000
3      4773919.000
4      7091230.000
...            ...
20398  8453746.000
20399  7074060.000
20400  1446785.000
20401  5490709.000
20402  8886555.000

[20403 rows x 1 columns]

In [56]:
MaxCIF_No['CIFRemarks']='OK'

In [57]:
MaxCIF_No['CIF_NO']=MaxCIF_No['CIF_NO'].astype(str)

In [58]:
del_dump_it['CIF_NO']=del_dump_it['CIF_NO'].astype(str)

In [59]:
del_dump_max=pd.merge(del_dump_it,MaxCIF_No[['CIF_NO','CIFRemarks']],on='CIF_NO',how='left')
del_dump_max

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,REV_GV,CHARGEDESC,RECEIVABLES_OTHEROD,Day_grp,PROday_grp,Deli_Remarks,CIF_NO,NPA_STAGEID,SMA_STAGE,CIFRemarks
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,,,NaN,'3-6,'3-6,Normal,9811944.0,REGULAR,NRML,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,,,NaN,'3-6,'3-6,Normal,9725968.0,REGULAR,NRML,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,,,NaN,'3-6,'3-6,Normal,9537813.0,REGULAR,SMA1,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,,,NaN,'3-6,'3-6,Normal,12020607.0,REGULAR,NRML,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,,,NaN,'3-6,'3-6,Normal,8342220.0,REGULAR,NRML,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,,,NaN,'3-6,'3-6,Normal,6753610.0,REGULAR,NRML,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,,,NaN,'3-6,'3-6,Normal,5490709.0,REGULAR,NPAS12,OK
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,,,NaN,'3-6,'3-6,Normal,8886555.0,REGULAR,NPAS12,OK
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,,,NaN,'6-7,'6-7,Normal,618521.0,REGULAR,NPA3,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,,,NaN,'3-6,'3-6,Normal,7074060.0,REGULAR,SMA0,OK

In [60]:
del_dump_max['Stage_Remarks']=np.where(
    (del_dump_max['SMA_STAGE']=='NPAS12'),
    'NPAS12',
    np.where(
        (~del_dump_max['CIFRemarks'].isna()) & (del_dump_max['CIFRemarks']=='OK'),
        'OK',
        'NO'
    )
    
)

In [61]:
del_dump_max

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,CHARGEDESC,RECEIVABLES_OTHEROD,Day_grp,PROday_grp,Deli_Remarks,CIF_NO,NPA_STAGEID,SMA_STAGE,CIFRemarks,Stage_Remarks
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,,NaN,'3-6,'3-6,Normal,9811944.0,REGULAR,NRML,NaN,NO
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,,NaN,'3-6,'3-6,Normal,9725968.0,REGULAR,NRML,NaN,NO
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,,NaN,'3-6,'3-6,Normal,9537813.0,REGULAR,SMA1,NaN,NO
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,,NaN,'3-6,'3-6,Normal,12020607.0,REGULAR,NRML,NaN,NO
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,,NaN,'3-6,'3-6,Normal,8342220.0,REGULAR,NRML,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,,NaN,'3-6,'3-6,Normal,6753610.0,REGULAR,NRML,NaN,NO
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,,NaN,'3-6,'3-6,Normal,5490709.0,REGULAR,NPAS12,OK,NPAS12
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,,NaN,'3-6,'3-6,Normal,8886555.0,REGULAR,NPAS12,OK,NPAS12
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,,NaN,'6-7,'6-7,Normal,618521.0,REGULAR,NPA3,NaN,NO
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,,NaN,'3-6,'3-6,Normal,7074060.0,REGULAR,SMA0,OK,OK

In [62]:
ff=del_dump_max[(del_dump_max['PRESENTATION_STATUS'].isin(["DRE","PENDINGDRE","DREDRE"])) & (del_dump_max['NPA_STAGEID']!='WRITEOFF')]
f2=ff[['CIF_NO']].drop_duplicates()

f2.to_csv("C:\\Users\\natrajsekarvs\\Downloads\\CHQMaxCIF_NO.csv",index=False)

In [63]:
CHQMaxCIF_NO=pd.read_csv(r'C:\Users\natrajsekarvs\Downloads\CHQMaxCIF_NO.csv')
CHQMaxCIF_NO

          CIF_NO
0    8608425.000
1    7722655.000
2    8139820.000
3   10060437.000
4    8662595.000
..           ...
117 10488150.000
118 12734231.000
119  9716684.000
120 13773204.000
121  9725451.000

[122 rows x 1 columns]

In [64]:
CHQMaxCIF_NO['CHQCIFRemarks']='OK'

In [65]:
CHQMaxCIF_NO['CIF_NO']=CHQMaxCIF_NO['CIF_NO'].astype(str)

In [66]:
del_dump_chq=pd.merge(del_dump_max,CHQMaxCIF_NO[['CIF_NO','CHQCIFRemarks']],on='CIF_NO',how='left')
del_dump_chq

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,RECEIVABLES_OTHEROD,Day_grp,PROday_grp,Deli_Remarks,CIF_NO,NPA_STAGEID,SMA_STAGE,CIFRemarks,Stage_Remarks,CHQCIFRemarks
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NaN,'3-6,'3-6,Normal,9811944.0,REGULAR,NRML,NaN,NO,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NaN,'3-6,'3-6,Normal,9725968.0,REGULAR,NRML,NaN,NO,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,NaN,'3-6,'3-6,Normal,9537813.0,REGULAR,SMA1,NaN,NO,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NaN,'3-6,'3-6,Normal,12020607.0,REGULAR,NRML,NaN,NO,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NaN,'3-6,'3-6,Normal,8342220.0,REGULAR,NRML,NaN,NO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,NaN,'3-6,'3-6,Normal,6753610.0,REGULAR,NRML,NaN,NO,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,NaN,'3-6,'3-6,Normal,5490709.0,REGULAR,NPAS12,OK,NPAS12,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,NaN,'3-6,'3-6,Normal,8886555.0,REGULAR,NPAS12,OK,NPAS12,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,NaN,'6-7,'6-7,Normal,618521.0,REGULAR,NPA3,NaN,NO,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,NaN,'3-6,'3-6,Normal,7074060.0,REGULAR,SMA0,OK,OK,NaN

In [67]:
del_dump_chq['ChequePRE_Status']=np.where(
    (del_dump_chq['PRESENTATION_STATUS'].isin(['DRE','PENDINGDRE','DREDRE'])),
    'CHQ_DRE',
    np.where(
        (~del_dump_chq['CHQCIFRemarks'].isna()) & (del_dump_chq['CHQCIFRemarks']=='OK'),
        'OK',
        'NO'
    )
    
)

In [68]:
del_dump_chq['CONCAT']=del_dump_chq['PRODUCT_FLAG'] + del_dump_chq['ASSETTYPE']+ del_dump_chq['SUBPRODUCT']

In [69]:
del_dump_sub=pd.merge(del_dump_chq,sub_prod_mast[['CONCAT','SUB_PROD','Sale_Product']],on='CONCAT',how='left')
del_dump_sub

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,CIF_NO,NPA_STAGEID,SMA_STAGE,CIFRemarks,Stage_Remarks,CHQCIFRemarks,ChequePRE_Status,CONCAT,SUB_PROD,Sale_Product
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,9811944.0,REGULAR,NRML,NaN,NO,NaN,NO,SHUBHUSEDCAR,USED CAR,USED PV
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,9725968.0,REGULAR,NRML,NaN,NO,NaN,NO,TRACTORNEWTRACTOR,TRACTOR,NEW TRACTOR
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,9537813.0,REGULAR,SMA1,NaN,NO,NaN,NO,SHUBHUSEDHCV,USED HCV,USED CV
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,12020607.0,REGULAR,NRML,NaN,NO,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,8342220.0,REGULAR,NRML,NaN,NO,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,6753610.0,REGULAR,NRML,NaN,NO,NaN,NO,VFPRIMEUSEDHCV,USED HCV,USED CV
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,5490709.0,REGULAR,NPAS12,OK,NPAS12,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,8886555.0,REGULAR,NPAS12,OK,NPAS12,NaN,NO,VFPRIMEUSEDLCV,USED LCV,USED CV
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,618521.0,REGULAR,NPA3,NaN,NO,NaN,NO,VFPRIMEUSEDLCV,USED LCV,USED CV
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,7074060.0,REGULAR,SMA0,OK,OK,NaN,NO,VFPRIMEUSEDMUV,USED MUV,USED PV

In [70]:
del_dump_sub.loc[del_dump_sub['SUB_PROD'].isna(),'CONCAT'].unique()

array([], dtype=object)

In [71]:
zone_mast.rename(columns={'FINAL BRANCH':'BRANCH_NAME'},inplace=True)

In [72]:
del_dump_zone=pd.merge(del_dump_sub,zone_mast[['BRANCH_NAME','ZONE','STATE HEAD','REGION','AREA','BRANCH']],on='BRANCH_NAME',how='left')
del_dump_zone

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,CHQCIFRemarks,ChequePRE_Status,CONCAT,SUB_PROD,Sale_Product,ZONE,STATE HEAD,REGION,AREA,BRANCH
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,NaN,NO,SHUBHUSEDCAR,USED CAR,USED PV,SOUTH,KARNATAKA,KARNATAKA 3,DAVANGRE,DAVANGRE
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,NaN,NO,TRACTORNEWTRACTOR,TRACTOR,NEW TRACTOR,SOUTH,AP & TELANGANA,TELANGANA 2,MIRYALAGUDA,SURYAPET
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,NaN,NO,SHUBHUSEDHCV,USED HCV,USED CV,SOUTH,TAMIL NADU,TN_4,THANJAVUR,ARIYALUR
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV,SOUTH,TAMIL NADU,TN_5,NAMAKKAL,RASIPURAM
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV,NORTH,DELHI & HARYANA,DELHI 2,MEERUT,MEERUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,NaN,NO,VFPRIMEUSEDHCV,USED HCV,USED CV,EAST,CHATTISGARH,CHATTISGARH 1,TILDA,DHARSIWA
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,NaN,NO,VFPRIMENEWLCV,NEW LCV,NEW CV,EAST,NORTH EAST,NORTH EAST 1,NAGAON,NAGAON
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,NaN,NO,VFPRIMEUSEDLCV,USED LCV,USED CV,NORTH,DELHI & HARYANA,HARYANA 1,KARNAL,KARNAL
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,NaN,NO,VFPRIMEUSEDLCV,USED LCV,USED CV,EAST,WESTBENGAL,WEST BENGAL 1,KOLKATA,KOLKATA
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,NaN,NO,VFPRIMEUSEDMUV,USED MUV,USED PV,WEST,MAHARASHTRA STATE 1,MH5,DHULE,SHIRPUR

In [73]:
del_dump_zone.loc[del_dump_zone['ZONE'].isna(),'BRANCH_NAME'].unique()

array([], dtype=object)

In [74]:
del_dump_pd=pd.merge(del_dump_zone,pd_mast[['AGREEMENTNO','SEASONING GRP','PAID TENURE GRP','Final Status','POS Comfort Flag','Last Month_Stage','Last Month_Deli-Remarks']],on='AGREEMENTNO',how='left')
del_dump_pd

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,STATE HEAD,REGION,AREA,BRANCH,SEASONING GRP,PAID TENURE GRP,Final Status,POS Comfort Flag,Last Month_Stage,Last Month_Deli-Remarks
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,KARNATAKA,KARNATAKA 3,DAVANGRE,DAVANGRE,'7-12,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,AP & TELANGANA,TELANGANA 2,MIRYALAGUDA,SURYAPET,'13-18,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,TAMIL NADU,TN_4,THANJAVUR,ARIYALUR,'7-12,PAID <25%,Paid 0 out of 2,NaN,Stage 2,PRE X-U
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,TAMIL NADU,TN_5,NAMAKKAL,RASIPURAM,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,DELHI & HARYANA,DELHI 2,MEERUT,MEERUT,'25-35,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,CHATTISGARH,CHATTISGARH 1,TILDA,DHARSIWA,'13-18,PAID 50%-74%,Paid 0 out of 4,NaN,NaN,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,NORTH EAST,NORTH EAST 1,NAGAON,NAGAON,'36+,PAID >=75%,Paid 0 out of 2,NaN,NaN,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,DELHI & HARYANA,HARYANA 1,KARNAL,KARNAL,'25-35,PAID 25%-49%,Paid 0 out of 1,NaN,NaN,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,WESTBENGAL,WEST BENGAL 1,KOLKATA,KOLKATA,'25-35,PAID 50%-74%,Paid 1 out of 2,NaN,NaN,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,MAHARASHTRA STATE 1,MH5,DHULE,SHIRPUR,'7-12,PAID <25%,Paid 4 out of 4,NaN,NaN,NaN

In [75]:
del_dump_pd.loc[del_dump_pd['SEASONING GRP'].isna(),'AGREEMENTNO'].unique()

array([], dtype=object)

In [76]:
del_dump_pre=pd.merge(del_dump_pd,pre_x[['AGREEMENTNO','PREX']],on='AGREEMENTNO',how='left')
del_dump_pre

,AGREEMENTNO,PROPOSALID,CUSTOMER_ID,PRODUCT_FLAG,ASSETTYPE,CATGDESC,SUBPRODUCT,PRODUCT,PRODUCT_GROUP,BRANCH_NAME,...,REGION,AREA,BRANCH,SEASONING GRP,PAID TENURE GRP,Final Status,POS Comfort Flag,Last Month_Stage,Last Month_Deli-Remarks,PREX
0,XSHUDAV00005613273,6164282.000,11919052.000,SHUBH,USED,CAR,CAR,PV,SHUBH PV@S,DAVANGRE VF,...,KARNATAKA 3,DAVANGRE,DAVANGRE,'7-12,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal,NaN
1,XTRAURY00004838916,98472729.000,8202452.000,TRACTOR,NEW,TRACTOR,TRACTOR,TRACTOR,NEW TRACTOR,SURYAPET VF,...,TELANGANA 2,MIRYALAGUDA,SURYAPET,'13-18,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal,NaN
2,XSHUARI00005864298,7233298.000,13411647.000,SHUBH,USED,HCV,HCV,CV,SHUBH CV@S,ARIYALUR VF,...,TN_4,THANJAVUR,ARIYALUR,'7-12,PAID <25%,Paid 0 out of 2,NaN,Stage 2,PRE X-U,NaN
3,XVFPRSI00005727100,6721744.000,12703032.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,RASIPURAM VF,...,TN_5,NAMAKKAL,RASIPURAM,'7-12,PAID <25%,Paid 4 out of 4,NaN,Stage 1,Normal,NaN
4,XVFPMEE00004211795,96536091.000,5448820.000,VFPRIME,NEW,LCV,LCV,CV,NEW CV@S,MEERUT VF,...,DELHI 2,MEERUT,MEERUT,'25-35,PAID 25%-49%,Paid 4 out of 4,NaN,Stage 1,Normal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527806,XVFPDHS00005314351,NaN,NaN,VFPRIME,USED,,HCV,,,DHARSIWA VF,...,CHATTISGARH 1,TILDA,DHARSIWA,'13-18,PAID 50%-74%,Paid 0 out of 4,NaN,NaN,NaN,NaN
2527807,XVFPNGA00002525976,NaN,NaN,VFPRIME,NEW,,LCV,,,NAGAON VF,...,NORTH EAST 1,NAGAON,NAGAON,'36+,PAID >=75%,Paid 0 out of 2,NaN,NaN,NaN,NaN
2527808,XVFPKAL00004472403,NaN,NaN,VFPRIME,USED,,LCV,,,KARNAL VF,...,HARYANA 1,KARNAL,KARNAL,'25-35,PAID 25%-49%,Paid 0 out of 1,NaN,NaN,NaN,NaN
2527809,XVFPKAT00004232808,NaN,NaN,VFPRIME,USED,,LCV,,,KOLKATTA VF,...,WEST BENGAL 1,KOLKATA,KOLKATA,'25-35,PAID 50%-74%,Paid 1 out of 2,NaN,NaN,NaN,NaN
2527810,XVFPSPH00005481420,NaN,NaN,VFPRIME,USED,,MUV,,,SHIRPUR VF,...,MH5,DHULE,SHIRPUR,'7-12,PAID <25%,Paid 4 out of 4,NaN,NaN,NaN,NaN

In [77]:
del_dump_pre.loc[del_dump_pre['PREX'].isna(),'AGREEMENTNO'].unique()

array(['XSHUDAV00005613273', 'XTRAURY00004838916', 'XSHUARI00005864298',
       ..., 'XVFPKAL00004472403', 'XVFPKAT00004232808',
       'XVFPSPH00005481420'], dtype=object)

In [78]:
del_dump_pre.replace({pd.NA: ""},inplace=True)

In [79]:
del_dump_pre['stage']=del_dump_pre['FINAL_CLNPA_DPD_GRP'].apply(
    lambda x: 'Stage 1' if x =="'0-1" else (
        'Stage 2' if x in ["'1-2","'2-3"] else 'Stage 3'
    )
)

In [80]:
del_dump_pre['PREX_Status']=del_dump_pre.apply(
    lambda row: 'Remove' if row['PREX'] == 'Yes' and row['COVID_STAGE'] =='' and row['stage']=='Stage 2' else 'OK',
    axis=1
)

In [81]:
del_dump_pre['Deli_Remarks']=del_dump_pre.apply(
    lambda x: x['COVID_STAGE'] if x['Deli_Remarks']=='Normal' and x['COVID_STAGE']!='' else x['Deli_Remarks'],
    axis=1
)

In [82]:
del_dump_pre['STAGE_REMARKS'] = del_dump_pre.apply(
    lambda row: (
        "'6-7" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'6-7" else (
            "'7-12" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'7-12" else (
                "'12-24" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'12-24" else (
                    "'24-36" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'24-36" else (
                        "'36+" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'36+" else (
                            "'3-6" if row['stage'] == 'Stage 3' and row['Day_grp'] == "'3-6" else row['Stage_Remarks']
                        )
                    )
                )
            )
        )
    ),
    axis=1
)

In [83]:
del_dump_pre['Deli_Remarks'] = del_dump_pre.apply(
    lambda row: (
        row['COVID_STAGE'] if row['Deli_Remarks'] == 'Normal' and row['COVID_STAGE'] != "" and row['stage'] != 'Stage 3' else (
            'CLNPA_STAGE_1B' if row['STAGE_REMARKS'] == 'OK' and row['FINAL_CLNPA_DPD_GRP'] == "'0-1'" else (
                'STAGE_1B' if row['STAGE_REMARKS'] == 'NPAS12' and row['FINAL_CLNPA_DPD_GRP'] == "'0-1'" else (
                    'CLNPA_STAGE_2B' if row['STAGE_REMARKS'] == 'OK' and row['stage'] == 'Stage 2' else (
                        'STAGE_2B' if row['STAGE_REMARKS'] == 'NPAS12' and row['stage'] == 'Stage 2' else (
                            row['STAGE_REMARKS'] if row['stage'] == 'Stage 3' and row['Deli_Remarks'] not in ['CLNPA_3-7', 'CLNPA_7+'] else row['Deli_Remarks']
                        )
                    )
                )
            )
        )
    ),
    axis=1
)

In [84]:
del_dump_pre['Deli_Remarks'] = np.where(
    (del_dump_pre['Deli_Remarks'] == "Normal") & (del_dump_pre['COVID_STAGE'] != "") & (del_dump_pre['stage'] != "Stage 3"),
    del_dump_pre['COVID_STAGE'],
    np.where(
        (del_dump_pre['STAGE_REMARKS'] == "OK") & (del_dump_pre['FINAL_CLNPA_DPD_GRP'] == "'0-1"),
        "CLNPA_STAGE_1B",
        np.where(
            (del_dump_pre['STAGE_REMARKS'] == "NPAS12") & (del_dump_pre['FINAL_CLNPA_DPD_GRP'] == "'0-1"),
            "STAGE_1B",
            np.where(
                (del_dump_pre['STAGE_REMARKS'] == "OK") & (del_dump_pre['stage'] == "Stage 2"),
                "CLNPA_STAGE_2B",
                np.where(
                    (del_dump_pre['STAGE_REMARKS'] == "NPAS12") & (del_dump_pre['stage'] == "Stage 2"),
                    "STAGE_2B",
                    np.where(
                        (del_dump_pre['stage'] == "Stage 3") & (~del_dump_pre['Deli_Remarks'].isin(["CLNPA_3-7", "CLNPA_7+"])),
                        del_dump_pre['STAGE_REMARKS'],
                        del_dump_pre['Deli_Remarks']
                    )
                )
            )
        )
    )
)

In [85]:
del_dump_pre['Provision_Remarks'] = del_dump_pre.apply(
    lambda row: (
        row['Deli_Remarks'] if row['stage'] == 'Stage 2' else (
            row['ADDN_STG3'] if row['ADDN_STG3'] != '' else (
                'CLNPA_3-7' if row['Deli_Remarks'] == 'CLNPA_3-7' else (
                    'CLNPA_7+' if row['Deli_Remarks'] == 'CLNPA_7+' else row['PROday_grp']
                )
            )
        )
    ),
    axis=1
)

In [86]:
del_dump_pre['CLNPA_ADDS'] = del_dump_pre['Deli_Remarks'].apply(lambda x:'Include' if x != 'Normal' else "")

In [87]:
del_dump_pre['Prex_Remarks'] = del_dump_pre.apply(
    lambda x: 'Remove' if x['PREX']=='Yes' and x['CLNPA_ADDS'] !='Include' else '',
    axis=1
)

In [88]:
del_dump_pre['FINAL_CLNPA_DPD_GRP']=del_dump_pre.apply(
    lambda row: "'0-1" if row['Prex_Remarks']=='Remove' and row['FINAL_CLNPA_DPD_GRP'] != "'A/C Closed" else row['FINAL_CLNPA_DPD_GRP'],
    axis=1
)

In [89]:
del_dump_pre['Cheque_Status']=del_dump_pre.apply(
    lambda row: 'Cheque Under Deposition' if row['ChequePRE_Status']=='CHQ_DRE' else (
        'CLNPA_Cheque Under Deposition' if row['ChequePRE_Status']=='OK' and row['Deli_Remarks'] in ['CLNPA_3-7','CLNPA_7+'] else ''
    ),
    axis=1
)

In [90]:
dd=del_dump_pre[
    (del_dump_pre['NPA_STAGE_ID']=='REGULAR') &
    (~del_dump_pre['FINAL_CLNPA_DPD_GRP'].isin(["'0-1","'Repo","'A/C Closed"])) &
    (~del_dump_pre['Prex_Remarks'].isin(['Remove']))
]
columns_to_write=['AGREEMENTNO','SEASONING GRP','PAID TENURE GRP','Final Status','POS Comfort Flag','BRANCH_NAME','ZONE','STATE HEAD','REGION','AREA','BRANCH','CONCAT','SUB_PROD','Sale_Product','STAGE_REMARKS','FEB DPD','FEB DPD GRP','COVID_STAGE','ADDN_STG3','PROPOSALID','CUSTOMER_ID','PRODUCT_FLAG','ASSETTYPE','CATGDESC','SUBPRODUCT','PRODUCT','PRODUCT_GROUP','REPAY_MODE','CUR_REPAYMODE','NPA_STAGE_ID','FREQ','PRV_EMIOS','PRV_DPD','PRV_POS','PRV_OD_PLUS_POS','CYCLE','AVG_EMI','EMI','INSTLAMT','BILL_AMT','CURR_AGG_STATUS','CURR_POS','CUR_OD_PLUS_POS','REV_CUR_OD_PLUS_POS','FINAL_NEW_DPD','FINAL_NEW_DPD_GRP','CURR_NPA_STAGEID','CHQ_STATUS','PRESENTATION_STATUS','CURR_DPD','ALLOCATION_DPD','ALLOCATION_DPD_GRP','ROLLRATE_STATUS','NEW_DPD','CURR_DPDSLABS','CLNPA_REAGE','CURR_EMIOS','COLL_EMI','REV_CURR_EMIOS','REV_CUR_DPD','REV_CURR_DPDSLABS','REV_ROLLRATE_STATUS','FLAG','EMP_ID','EMP_NAME','BOUNCE_REMARKS','OTHER_OD_DPD','REVISED_FINAL_DPD','MI_SHORT_AMOUNT','CUSTOMERNAME','CLNPA_CIFNO','CLNPA_GRP','LEGAL_INFO','PRIORITY_INFO','POS_COMFORT_GIVEN','UNPAID','POS_COMFORT_STATUS','STABLI_UNPAID','MORATORIUM','MORATORIUM_PERIOD','FINAL_CLNPA_DPD_GRP','Day_grp','Deli_Remarks','Provision_Remarks','stage','Stage_Remarks','CHARGEDESC','RECEIVABLES_OTHEROD','Last Month_Stage','Last Month_Deli-Remarks','Cheque_Status']
dd[columns_to_write].to_csv("C:\\Users\\natrajsekarvs\\Downloads\\Agmt Level 1_plus.csv",index=False)

In [91]:
DailySummary = del_dump_pre[del_dump_pre['NPA_STAGE_ID'] == 'REGULAR'] \
    .groupby(['BRANCH', 'CONCAT', 'PRODUCT', 'SUB_PROD', 'FINAL_NEW_DPD_GRP', 'FINAL_CLNPA_DPD_GRP', 'ADDN_STG3', 'Deli_Remarks', 'SEASONING GRP']) \
    .agg(REV_CUR_OD_PLUS_POS=('REV_CUR_OD_PLUS_POS', 'sum')) \
    .reset_index()

DailySummary.to_csv("C:\\Users\\natrajsekarvs\\Downloads\\Daily Del Summary.csv", index=False)

In [92]:
result1 = del_dump_pre[(del_dump_pre['NPA_STAGE_ID'] == 'REGULAR') & ((del_dump_pre['Deli_Remarks'] == 'CLNPA_STAGE_1B') | (del_dump_pre['Deli_Remarks'] == 'STAGE_1B'))] \
    .assign(Remarks=lambda x: np.where(x['CLNPA_GRP'] == "'3-4", "VF CLNPA", np.where(~x['ADDN_STG3'].isin([None, np.nan, ""]), x['ADDN_STG3'], x['Deli_Remarks']))) \
    .rename(columns={'FINAL_NEW_DPD': 'DPD Without CLNPA', 
                     'FINAL_NEW_DPD_GRP': 'DPD Grp Without CLNPA',
                     'REV_CUR_OD_PLUS_POS':'GV',
                     'FINAL_CLNPA_DPD_GRP': 'DPD Grp With CLNPA'}) \
    .loc[:, ['AGREEMENTNO', 'PRODUCT', 'SUB_PROD', 'GV', 'DPD Without CLNPA', 'DPD Grp Without CLNPA', 'CUSTOMERNAME',
             'STATE HEAD', 'REGION', 'AREA', 'BRANCH', 'EMP_ID', 'EMP_NAME', 'CLNPA_CIFNO', 'Remarks', 'DPD Grp With CLNPA', 'SEASONING GRP',
             'PAID TENURE GRP', 'Final Status', 'POS Comfort Flag', 'ADDN_STG3', 'Deli_Remarks', 'Provision_Remarks', 'Last Month_Stage', 'Last Month_Deli-Remarks']] \
    .to_csv("C:\\Users\\natrajsekarvs\\Downloads\\1B&1BCLNPA_Agmt_level.csv", index=False)

In [93]:
del_dump_pre['dhinesh']=del_dump_pre.apply(lambda row: 'Remove' if row['FINAL_CLNPA_DPD_GRP']=="'0-1" and row['Deli_Remarks']=='Normal' else 'Consider',axis=1)

In [94]:
fd=del_dump_pre[(del_dump_pre['NPA_STAGE_ID']=='REGULAR') & 
                (~del_dump_pre['FINAL_CLNPA_DPD_GRP'].isin(["'Repo","'A/C Closed"])) &
                (del_dump_pre['dhinesh'].isin(['Consider']))]

select_columns_d=['AGREEMENTNO','FINAL_CLNPA_DPD_GRP','Deli_Remarks','stage','dhinesh']

fd1=fd[select_columns_d]

fd1.to_csv("C:\\Users\\natrajsekarvs\\Downloads\\Dhinesh.csv", index=False)

In [95]:
region_list = del_dump_pre.loc[~del_dump_pre['REGION'].isin([None, pd.NA, "", np.nan]), 'REGION'].unique().tolist()

In [96]:
#region_list=del_dump_pre.loc[~del_dump_pre['REGION'].isin([None,'NaN','']), 'REGION'].unique()

In [97]:
import os

In [98]:
output_directory = "C:\\Users\\natrajsekarvs\\Downloads\\region"

# Create the output directory if it doesn't exist
os.makedirs(output_directory, exist_ok=True)

for reg_name in region_list:
    region_filtered = del_dump_pre[(del_dump_pre['NPA_STAGE_ID'] == 'REGULAR') & 
                               (~del_dump_pre['FINAL_CLNPA_DPD_GRP'].isin(["'0-1", "'Repo", "'A/C Closed"])) &
                               (~del_dump_pre['Prex_Remarks'].isin(["Remove"])) &
                               (del_dump_pre['REGION'] == reg_name)] \
                               .rename(columns={'FINAL_NEW_DPD': 'DPD Without CLNPA', 
                                                'FINAL_NEW_DPD_GRP': 'DPD Grp Without CLNPA',
                                                'REV_CUR_OD_PLUS_POS':'GV',
                                                'FINAL_CLNPA_DPD_GRP': 'DPD Grp With CLNPA'}) \
                               .loc[:, ['AGREEMENTNO', 'PRODUCT', 'SUB_PROD', 'Sale_Product', 'GV',
                                        'DPD Without CLNPA', 'DPD Grp Without CLNPA', 'CUSTOMERNAME', 'ZONE', 'STATE HEAD',
                                        'REGION', 'AREA', 'BRANCH', 'EMP_ID', 'EMP_NAME', 'CLNPA_CIFNO',
                                        'Deli_Remarks', 'Provision_Remarks', 'DPD Grp With CLNPA', 'SEASONING GRP',
                                        'PAID TENURE GRP', 'Final Status', 'POS Comfort Flag', 'ADDN_STG3',
                                        'CHARGEDESC', 'RECEIVABLES_OTHEROD', 'stage', 'Last Month_Stage',
                                        'Last Month_Deli-Remarks', 'Cheque_Status']] \
                               .sort_values(by=['REGION', 'AREA', 'BRANCH'])
    
    output_file_path = os.path.join(output_directory, f"REGION_{reg_name}.csv")
    region_filtered.to_csv(output_file_path, index=False)

In [99]:
zone_list = del_dump_pre.loc[~del_dump_pre['ZONE'].isin([None, pd.NA, "", np.nan]), 'ZONE'].unique().tolist()

In [100]:
output_directory_zone = "C:\\Users\\natrajsekarvs\\Downloads\\zone"

# Create the output directory if it doesn't exist
os.makedirs(output_directory_zone, exist_ok=True)

for zone_name in zone_list:
    zone_filtered = del_dump_pre[(del_dump_pre['NPA_STAGE_ID'] == 'REGULAR') & 
                             (~del_dump_pre['FINAL_CLNPA_DPD_GRP'].isin(["'0-1", "'Repo", "'A/C Closed"])) &
                             (~del_dump_pre['Prex_Remarks'].isin(["Remove"])) &
                             (del_dump_pre['ZONE'] == zone_name)] \
                             .rename(columns={'FINAL_NEW_DPD': 'DPD Without CLNPA', 
                                                'FINAL_NEW_DPD_GRP': 'DPD Grp Without CLNPA',
                                                'REV_CUR_OD_PLUS_POS':'GV',
                                                'FINAL_CLNPA_DPD_GRP': 'DPD Grp With CLNPA'}) \
                             .loc[:, ['AGREEMENTNO', 'PRODUCT', 'SUB_PROD', 'Sale_Product', 'GV',
                                      'DPD Without CLNPA', 'DPD Grp Without CLNPA', 'CUSTOMERNAME', 'ZONE', 'STATE HEAD',
                                      'REGION', 'AREA', 'BRANCH', 'EMP_ID', 'EMP_NAME', 'CLNPA_CIFNO',
                                      'Deli_Remarks', 'Provision_Remarks', 'DPD Grp With CLNPA', 'SEASONING GRP',
                                      'PAID TENURE GRP', 'Final Status', 'POS Comfort Flag', 'ADDN_STG3',
                                      'CHARGEDESC', 'RECEIVABLES_OTHEROD', 'stage', 'Last Month_Stage',
                                      'Last Month_Deli-Remarks', 'Cheque_Status']] \
                             .sort_values(by=['REGION', 'AREA', 'BRANCH'])
    
    output_file_path1 = os.path.join(output_directory_zone, f"ZONE_{zone_name}.csv")
    zone_filtered.to_csv(output_file_path1, index=False)